trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  npm_config_cache: $(System.DefaultWorkingDirectory)/node_modules

jobs:
- job: Build_and_Test
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install'

  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: '$(npm_config_cache)'
      
  - script: |
      npm run knex:migrate
      npm run test
    displayName: 'Test'

  - script: |
      npm run lint
    displayName: 'Lint'

  - script: |
      npm run audit
    displayName: 'Security Audit'

- job: SonarCloud
  dependsOn: Build_and_Test
  steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'rafaelsouza0095'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'RafaelSouza0095_exp-mgmt-svc'
      cliProjectName: 'exp-mgmt-svc'
      cliProjectVersion: '0.0.1'
      cliSources: '.'
      sonar.javascript.lcov.reportPaths: './coverage/'

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'