name: Develop_Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - name: npm install
        run: npm install
      - name: Test
        run: |
          npm run knex:migrate
          npm run test
      
