name: Develop_Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - name: npm install
        run: npm install
      - name: Test
        run: |
          npm run knex:migrate
          npm run test
      - name: Lint
        run: npm run lint
      - name: Security Audit
        run: npm run audit
      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build and Push
        uses: docker/build-push-action@v2.4.0
          
